### ISSUE TITLE
Simple intialization is failing

### ISSUE THREAD

**Issue by FloryanFilip** [DHTMLX/vue-gantt-demo#20]
After installing the project via npm install and trying to render the provided components I get this error in the console

![Zrzut ekranu 2021-04-27 o 15 46 25](https://user-images.githubusercontent.com/23243818/116252347-c730ba80-a76f-11eb-955e-e5c455fc2c1b.png)

```
<template>
    <MaterialTheme>
      <Gantt :tasks="tasks" :links="links" :scales="scales" :columns="columns" />
    </MaterialTheme>
</template>

<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator';
import { Gantt, MaterialTheme } from '@dhtmlx/trial-vue-gantt';

@Component({
  components: {
    Gantt,
    MaterialTheme,
  },
})
export default class InspireComponent extends Vue {
  scales = [...];

  columns = [...];

  tasks = [...];

  links = [...];
}
```

**Comment by gearcoded** [comment]
@FloryanFilip,
It seems that you confused the components. This is a demo for the DHTMLX Javascript Gantt and you try to install the DHTMLX Vue Gantt component. These are completely different components that have different codebase and features. 

If you want to install the Trial version of the Javascript Gantt as an NPM package, you can do it the following way:
1) Unpack Gantt to a specific folder, for example, to /opt/gantt_pro
2) Use the following command to install Gantt:
```
npm install /opt/gantt_pro
```

You can read more about installation methods in the following article:
https://docs.dhtmlx.com/gantt/desktop__install_with_bower.html#addingproeditionintoproject



To use the Vue Gantt, you need to refer to the following repository and article:
https://github.com/web-widgets/vue-gantt-demos
https://docs.dhtmlx.com/gantt/web__vue.html
